export const eventsQuery = `query
    {
      games{
          id
          creator{
            username
            fullname
            avatar
          }
          title
          description
          type
          subtype
          location
          from
          to
          invited{
            username
            fullname
            avatar
          }
          accepted{
            username
            fullname
            avatar
          }
          declined{
            username
            fullname
            avatar
          }
          unresponsive{
            username
            fullname
            avatar
          }
          updatedAt
          createdAt
      }
    }
`
