export const eventsQuery = `query
    {
      games{
          id
          creator{
            username
            fullName
            avatar
          }
          title
          description
          type
          subtype
          location
          from
          to
          invited
          accepted
          declined
          unresponsive
          updatedAt
          createdAt
      }
    }
`
