#!/bin/bash
source ~/.bashrc
PATH=$PATH:~/.nvm/versions/node/v9.3.0/bin:~/.nvm/
~/.nvm/nvm.sh
nvm use 9.3.0
pm2 delete pokerface
GIT_WORK_TREE=~/Desktop/apps/pokerface/server git checkout -f
pushd ~/Desktop/apps/pokerface/server
yarn
yarn run migrate
yarn run build
NODE_ENV=production GMAIL_USER=user GMAIL_PASSWORD=password POSTGRES_USER=user POSTGRES_PASSWORD=password pm2 start dist/index.js --name pokerface -i 0
popd
