#!/bin/bash
source ~/.bashrc
PATH=$PATH:~/.nvm/versions/node/v11.10.1/bin:~/.nvm/
~/.nvm/nvm.sh
nvm use 11.10.1
GIT_WORK_TREE=~/Desktop/apps/pokerface git checkout -f
pushd ~/Desktop/apps/pokerface/client
yarn --ignore-engines
# yarn add https://github.com/deanshub/draft-js#android-fix --ignore-engines
yarn run build
popd
pm2 delete pokerface
pushd ~/Desktop/apps/pokerface/server
yarn
NODE_ENV=production yarn run migrate
NODE_ENV=production yarn run build
NODE_ENV=production GMAIL_USER=user GMAIL_PASSWORD=password POSTGRES_USER=user POSTGRES_PASSWORD=password pm2 start dist/index.js --name pokerface -i 0
popd
